### ISSUE TITLE
bios如何设置

### ISSUE THREAD

**Issue by yunweichen** [Guanhang/Lenovo-13isk-xiaoxin-air13pro-OpenCore-EFI#1]
bios版本和设置是什么样子的呢，感谢。

**Comment by Guanhang** [comment]
BIOS：3GCN25WW
设置要进高级模式吧cfg lock 关掉
还有其他的改一点点

**Comment by yunweichen** [comment]
感谢，bios 已升级到3GCN25WW， 高级模式中cfg lock 关掉了，其他的改动有什么文章教程么？

**Comment by Guanhang** [comment]
如果你按照大多数黑果安装教程操作那基本上没有了，试过了吗？

**Comment by yunweichen** [comment]
有试过，可能我硬盘还没换掉，进不到装机页面

**Comment by Guanhang** [comment]
你用的是黑果小兵的安装包吗？放到u盘然后替换我的efi就可以啊，跟硬盘没什么关系

**Comment by yunweichen** [comment]
没，用的是平台appstore 下载的，然后制作的安装盘，替换了EFI的。不知是不是bios 还是漏了哪个

**Comment by Guanhang** [comment]
不应该啊，secure Boot，还有USB 启动有没有改？ 要是还不行去下个黑果小兵的包
